#!/usr/bin/env bash
# Run the Unity pipeline on the licensed Linux build VM (kiki-unity) and sync results back.
#   Tools/remote.sh push | pull | setup | content [args] | build [mac,win,linux] | method <Class.Method> [args] | log <name> [n]
# The VM is shared with other Unity projects: we wait until no other project's editor is running before launching
# ours (a starting editor can restart the licensing client and hang a batch run that is already going), and every
# run is wrapped in a timeout.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOST="${SM_HOST:-kiki-unity}"
RDIR="${SM_RDIR:-Projects/saltmoss-harbor}"
RUNITY="${SM_RUNITY:-\$HOME/Unity/6000.3.20f1/Editor/Unity}"
EXCL=(--exclude Library/ --exclude Temp/ --exclude Logs/ --exclude UserSettings/ --exclude Obj/ --exclude Build/ --exclude '*.csproj' --exclude '*.sln' --exclude .DS_Store)
GEN=(--exclude 'Assets/Saltmoss/Generated/' --exclude 'Assets/Saltmoss/Generated.meta' --exclude 'Assets/Saltmoss/Scenes/' --exclude 'Assets/Saltmoss/Scenes.meta' --exclude 'Assets/Saltmoss/Settings/' --exclude 'Assets/Saltmoss/Settings.meta' --exclude 'ProjectSettings/' --exclude 'Packages/packages-lock.json' --exclude 'Assets/Saltmoss/Resources/*.asset' --exclude 'Assets/Saltmoss/Resources/*.mat' --exclude 'Assets/Saltmoss/Resources/*.asset.meta' --exclude 'Assets/Saltmoss/Resources/*.mat.meta')

wait_idle() {
  local waited=0
  while ssh "$HOST" "pgrep -af '[E]ditor/Unity .*-projectPath' | grep -v 'saltmoss-harbor' | grep -q ." ; do
    if (( waited == 0 )); then echo "== VM busy with another project's Unity; waiting…"; fi
    sleep 20; waited=$((waited + 20))
    if (( waited > 5400 )); then echo "!! gave up waiting for the VM after 90 min"; exit 3; fi
  done
  if (( waited > 0 )); then echo "== VM idle after ${waited}s"; sleep 5; fi
}

push() {
  ssh "$HOST" "mkdir -p $RDIR/Game/ProjectSettings $RDIR/logs $RDIR/Builds"
  # sources replace the remote copy (stale scripts would break compilation); Unity-owned/generated files are
  # excluded (and so protected from --delete), metas are never deleted remotely
  rsync -az --delete "${EXCL[@]}" "${GEN[@]}" --exclude 'Assets/Saltmoss/Materials/' --filter 'P *.meta' \
        "$ROOT/Game/" "$HOST:$RDIR/Game/"
  rsync -az --ignore-existing "$ROOT/Game/ProjectSettings/" "$HOST:$RDIR/Game/ProjectSettings/"
}

pull() {
  # Unity-authored metas come back (only ones we don't have), plus settings and the lock file
  rsync -az --ignore-existing --include '*/' --include '*.meta' --exclude '*' "${GEN[@]}" "$HOST:$RDIR/Game/Assets/" "$ROOT/Game/Assets/"
  rsync -az "$HOST:$RDIR/Game/ProjectSettings/" "$ROOT/Game/ProjectSettings/"
  rsync -az "$HOST:$RDIR/Game/Packages/packages-lock.json" "$ROOT/Game/Packages/" 2>/dev/null || true
  # materials are generated by ProjectSetup but kept in git
  rsync -az "$HOST:$RDIR/Game/Assets/Saltmoss/Materials/" "$ROOT/Game/Assets/Saltmoss/Materials/" 2>/dev/null || true
  # BankBuilder sets the audio import settings (music and ambiences stream); keep git in step so a push can't undo them
  rsync -az --include '*/' --include '*.meta' --exclude '*' "$HOST:$RDIR/Game/Assets/Saltmoss/Audio/" "$ROOT/Game/Assets/Saltmoss/Audio/"
}

run() {
  local name=$1; shift
  local limit=${SM_TIMEOUT:-5400}
  wait_idle
  echo "== remote $name: $*"
  set +e
  ssh "$HOST" "cd $RDIR && timeout $limit $RUNITY -batchmode -nographics -projectPath \$HOME/$RDIR/Game -logFile \$HOME/$RDIR/logs/$name.log $* ; echo EXIT=\$?" | tail -1
  set -e
  ssh "$HOST" "grep -E 'error CS|Exception|Shader error|\\[Pipeline\\]|\\[Build\\]|\\[Saltmoss\\]|\\[Gallery\\]|\\[World|Compilation failed|Scripts have compiler errors' $RDIR/logs/$name.log | grep -v 'UnityEngine.Debug' | head -80" || true
}

cmd=${1:-help}; shift || true
case $cmd in
  push) push ;;
  pull) pull ;;
  setup) push; run setup -quit -executeMethod Saltmoss.EditorTools.ProjectSetup.Run "$@"; pull ;;
  content) push; run content -executeMethod Saltmoss.EditorTools.Pipeline.Content "$@"; pull ;;
  build)
    plats=${1:-mac,win,linux}; shift || true
    push; run build -executeMethod Saltmoss.EditorTools.BuildScript.BuildAll -platforms "$plats" -out \$HOME/$RDIR/Builds "$@"
    mkdir -p "$ROOT/Builds"
    for p in ${plats//,/ }; do rsync -az --delete "$HOST:$RDIR/Builds/$p/" "$ROOT/Builds/$p/"; done
    [[ ",$plats," == *",mac,"* ]] && "$ROOT/Tools/mac_sign.sh" || true ;;
  all) push; run setup -quit -executeMethod Saltmoss.EditorTools.ProjectSetup.Run
       run content -executeMethod Saltmoss.EditorTools.Pipeline.Content
       pull
       plats=${1:-mac}
       run build -executeMethod Saltmoss.EditorTools.BuildScript.BuildAll -platforms "$plats" -out \$HOME/$RDIR/Builds
       mkdir -p "$ROOT/Builds"
       for p in ${plats//,/ }; do rsync -az --delete "$HOST:$RDIR/Builds/$p/" "$ROOT/Builds/$p/"; done
       [[ ",$plats," == *",mac,"* ]] && "$ROOT/Tools/mac_sign.sh" || true ;;
  method) m=$1; shift; push; run "${m##*.}" -executeMethod "$m" "$@"; pull ;;
  log) ssh "$HOST" "tail -n ${2:-80} $RDIR/logs/$1.log" ;;
  *) echo "usage: $0 push|pull|setup|content|build [plats]|all [plats]|method <Class.Method>|log <name> [n]" ;;
esac
